# Generated by Django 5.0.3 on 2024-03-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(choices=[('NW', 'Новости'), ('AR', 'Статья')], default='NW'),
        ),
    ]
