# Generated by Django 5.0.3 on 2024-03-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NW', 'Новости'), ('AR', 'Статья')], default='NW', max_length=2),
        ),
    ]
